; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32215.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f
PUBLIC	main
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.c
; Line 6
	xor	eax, eax
; Line 7
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT f
_TEXT	SEGMENT
f	PROC						; COMDAT
; File c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.c
; Line 3
	ret	0
f	ENDP
_TEXT	ENDS
END
