; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32215.0 

	TITLE	c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.c
; Line 5
	push	ebp
	mov	ebp, esp
; Line 6
	xor	eax, eax
; Line 7
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f	PROC
; File c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.c
; Line 1
	push	ebp
	mov	ebp, esp
; Line 3
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
END
