; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32215.0 

	TITLE	c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
PUBLIC	_main
; Function compile flags: /Ogtpy
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.c
; Line 6
	xor	eax, eax
; Line 7
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _f
_TEXT	SEGMENT
_f	PROC						; COMDAT
; File c:\Users\vboxuser\Desktop\reversing_study\empty_func\f.c
; Line 3
	ret	0
_f	ENDP
_TEXT	ENDS
END
